# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
  lane :release do
    build_ios_app
    export_method: 'app-store'
    upload_to_testflight
    build_app(scheme: "GrowERPadmin")
  end
  lane :submit_review do
    deliver(
      submit_for_review: true,
      force: true,
      skip_metadata: true,
      skip_screenshots: true,
      overwrite_screenshots: true,
      precheck_include_in_app_purchases: false
    )
  end
end
