name: ecommerce
description: A new Flutter package project.
version: 0.0.1
homepage: https://ecommerce.growerp.org
publish_to: none


environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter: 
    sdk: flutter
  decimal: ^2.1.0
  global_configuration: ^2.0.0-nullsafety.0
  equatable: ^2.0.3
  dio: ^4.0.0
  flutter_bloc: ^8.0.0
  meta: ^1.3.0
  shared_preferences: ^2.0.5
  about: ^2.0.0
  animations: ^2.0.0
  responsive_framework: ^0.2.0
  flutter_staggered_grid_view: ^0.4.0
  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_driver:
#    sdk: flutter
#  integration_test: ^1.0.2+2
  mockito: ^5.0.2
  very_good_analysis: ^2.0.0

  bloc_test: ^9.0.1
  flutter_launcher_icons: ^0.9.0

# to run icons: flutter pub run flutter_launcher_icons:main 
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/growerp.jpg"

flutter:
  uses-material-design: true
# from https://www.flaticon.com/
# https://creativemarket.com/eucalyp Eucalyp
  assets:
    - assets/cfg/
    - assets/images/
    - assets/
    - ./
