name: utils
description: A command-line applications to support the GrowERP system.
# version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  args: ^2.0.0
  path: ^1.8.0


dev_dependencies:
  pedantic: ^1.9.0


