# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

#  desc "Submit a new Beta Build to Crashlytics Beta"
#  lane :beta do
#    gradle(task: "clean assembleRelease")
#    crashlytics
#  
#    # sh "your_script.sh"
#    # You can also use other beta testing services here
#  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  lane :beta do
    # Adjust the `build_type` and `flavor` params as needed to build the right APK for your setup
    gradle(
      task: 'assemble',
      build_type: 'Release',
    )
    upload_to_play_store(
      track: 'beta',
      version_code: 5,
      skip_upload_changelogs: true,
      skip_upload_screenshots: true)
    end
end
