name: hotel
version: 0.2.0+10
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter: 
    sdk: flutter
  flutter_localizations:
        sdk: flutter
  global_configuration: ^2.0.0-nullsafety.0
  equatable: ^2.0.3
  dio: ^4.0.0
  flutter_bloc: ^8.0.0
  meta: ^1.3.0
  shared_preferences: ^2.0.6
  animations: ^2.0.0
  core:
    path: ../core
  package_info_plus: ^1.4.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  utils:
    path: ../utils
      
  mockito: ^5.0.3
  bloc_test: ^9.0.1
  flutter_launcher_icons: ^0.9.0
# to run icons: flutter pub run flutter_launcher_icons:main 
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/hotel1.jpg"

flutter:
  uses-material-design: true
# from https://www.flaticon.com/
  assets:
    - assets/images/
    - assets/cfg/
    - assets/
    - ./
